table Vacantes

	column 'sector'
		dataType: string
		summarizeBy: none
		sourceColumn: sector

	column 'company_name'
		dataType: string
		summarizeBy: none
		sourceColumn: company_name

	column 'country'
		dataType: string
		summarizeBy: none
		sourceColumn: country

	column 'seniority'
		dataType: string
		summarizeBy: none
		sourceColumn: seniority

	column 'title'
		dataType: string
		summarizeBy: none
		sourceColumn: title

	column 'source_platform'
		dataType: string
		summarizeBy: none
		sourceColumn: source_platform

	column 'continent'
		dataType: string
		summarizeBy: none
		sourceColumn: continent

	column 'posted_date'
		dataType: string
		summarizeBy: none
		sourceColumn: posted_date

	measure KPI_Vacantes = COUNTROWS(Vacantes)
		formatString: #,0.00
		displayFolder: Indicadores

	partition Vacantes = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Vacantes.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"sector", type text}, {"company_name", type text}, {"country", type text}, {"seniority", type text}, {"title", type text}, {"source_platform", type text}, {"continent", type text}, {"posted_date", type text}}, "en-US")
				in
				    Typed
